### ISSUE TITLE
Transmit default background is grey (was black)

### ISSUE THREAD

**Issue by craigerl** [ON4QZ/QSSTV#11]
Transmit pane, right-click, Load background. select [fit].   Image area not covered by the background image is grey.  It was black in previous releases.  Can we revert this easily back to black?   Black uses a more narrow bandwidth, gets through better imho.  thanks!

**Comment by Ruxton** [comment]
There's a setting for this:
![Untitled](https://user-images.githubusercontent.com/382760/200101691-bffbad31-b0d6-429b-b1f5-674d6fed6216.png)

**Comment by craigerl** [comment]
Yes!  thank you!
