### ISSUE TITLE
Required Plugins To Run Build??

### ISSUE THREAD

**Issue by vk6mo** [ON4QZ/QSSTV#24]
(sorry if this is a newbie question!!:( )

LM21.1 (clean install)
Using Qt6.5.0
No QtCreator installed
Both Main and development branch build successfully.
Attempting to run qsstv results in

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, vkkhrdisplay, eglfs, linuxfb, offscreen, xcb, minimalegl, vnc, minimal, wayland.

Aborted (core dumped)

If I set QT_DEBUG_PLUGINS=1, the output is in the following file
[RunOutput.txt](https://github.com/ON4QZ/QSSTV/files/11439003/RunOutput.txt)

**Comment by dl8dtl** [comment]
Well, the key is this error message:
```
qt.core.library: "/opt/Qt/6.5.0/gcc_64/plugins/platforms/libqxcb.so" cannot load: Cannot load library /opt/Qt/6.5.0/gcc_64/plugins/platforms/libqxcb.so: (libxcb-cursor.so.0: cannot open shared object file: No such file or directory)
```
So, you have to find out on your system how to install a package that provides `libxcb-cursor.so.0`.

**Comment by vk6mo** [comment]
Yes ... but ... I might be wrong but I would have thought dependencies should be part of the install??
FYI - the libraries required are:
libicu-dev
libxcb-cursor-dev
Might be something that is new to Qt6.5.0??

**Comment by vk6mo** [comment]
OK. Thanks. I will look at Qt installer and see if I can identify which group includes those libraries.
Qt installer only gives broad groups to install, not individual libraries.
Initial Qt install was as follows.
![QtInstallOptions](https://github.com/ON4QZ/QSSTV/assets/132327266/67cfff12-73fe-4d39-8738-53618435c8ea)
