### ISSUE TITLE
where is stored config file?

### ISSUE THREAD

**Issue by simona70** [ON4QZ/QSSTV#34]
hi, i recently tried to activate qsstv on my arch linux distro with a FT991A radio using rigctl. after setting up a seemingly broken configuration, i closed the app and restarted. when restarting it is very slow and you do practically nothing, including entering and changing the configuration from the appropriate menu. so I started looking for the configuration file, hoping it was an ascii format. I would like to delete it or modify it by hand in order to restart the application. but i can't find it. where is it?

**Comment by ON4QZ** [comment]
It's in your home directory ~/.config/ON4QZ/qsstv_9.0.conf

**Comment by simona70** [comment]
thx :-)

**Comment by simona70** [comment]
thx
