### ISSUE TITLE
wavio error

### ISSUE THREAD

**Issue by dwtaiden** [ON4QZ/QSSTV#40]
I use sound input from file modle，but when i choice wav file，it's have a error
![image](https://github.com/ON4QZ/QSSTV/assets/71805125/9a4bb2e7-4b6b-48e7-83a4-7905faaab9bd)

**Comment by dl8dtl** [comment]
I'm afraid, without also providing the file you are trying to open, no help will be possible.

**Comment by dwtaiden** [comment]
this is that file
[Uploading flag.zip…]()

**Comment by dl8dtl** [comment]
Sorry, where is the WAV file you want to open? Can you upload it here?

**Comment by dwtaiden** [comment]
[flag.zip](https://github.com/ON4QZ/QSSTV/files/13434449/flag.zip)
I try to upload the file

**Comment by ON4QZ** [comment]
Your wav file has a samplerate of 44100Hz, convert it (with e.g. Audacity) to 48000Hz.

**Comment by scribbles** [comment]
@ON4QZ Also experiencing this issue. Both files converted to 48000Hz wav with both ffmpeg and Audacity.  

```
$ ffmpeg -i sstv-essexham-image01-martin2.mp3 -ar 48000 sstv-essexham-image01-martin2.wav
<snip>
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, mono, s16, 768 kb/s
    Metadata:
      encoder         : Lavc58.134.100 pcm_s16le
size=    5579kB time=00:00:59.50 bitrate= 768.0kbits/s speed= 632x    
video:0kB audio:5579kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.003816%
```


Files:
[Essex Ham SSTV](https://www.essexham.co.uk/audio/sstv-essexham-image01-martin2.mp3)
[Sig Id Wiki](https://www.sigidwiki.com/wiki/File:SSTV_Scottie_1_LSB.7z)
